name: fedenv
channels:
  - defaults
dependencies:
  - python=3.13
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - pip
  - pip:
      - fqdn==1.5.1
      - isoduration==20.11.0
      - uri-template==1.3.0
      - webcolors==24.11.1
prefix: /opt/anaconda3
